Repository LotCom/LotCom-printer, pull requests merged in 2025-07, with the labels that each got.

#203 198-implement-print-history-reader
  LotCoMPrinter/Models/Datasources/PrintHistory.cs
  LotCoMPrinter/Models/Exceptions/DatabaseException.cs
  LotCoMPrinter/Models/Exceptions/ProcessNameException.cs
  LotCoMPrinter/packages.lock.json
Labels: enhancement

#205 feature/204
  CHANGELOG.md
  LotCoMPrinter/LotCoMPrinter.csproj
  LotCoMPrinter/Platforms/Windows/Package.appxmanifest
  LotCoMPrinter/Platforms/Windows/app.manifest
  LotCoMPrinter/packages.lock.json
Labels: enhancement

#209 Merge 'feature/199' and 'feature/197' branches
  LotCoMPrinter/Models/Datatypes/PrintJob.cs
  LotCoMPrinter/Models/Enums/PrintJobType.cs
  LotCoMPrinter/ViewModels/MainPageViewModel.cs
Labels: enhancement

#208 feature/197
  .github/workflows/cicd.yml
  LotCoMPrinter/Models/Datasources/PrintHistory.cs
  LotCoMPrinter/Models/Datatypes/PrintJob.cs
  LotCoMPrinter/Models/Enums/PrintJobType.cs
  LotCoMPrinter/Resources/Styles/Styles.xaml
  LotCoMPrinter/ViewModels/MainPageViewModel.cs
  LotCoMPrinter/Views/MainPage.xaml
  LotCoMPrinter/Views/MainPage.xaml.cs
  LotCoMPrinter/Views/ProcessSelectionPopup.xaml
  LotCoMPrinter/Views/ProcessSelectionPopup.xaml.cs
  LotCoMPrinter/Views/ReprintListPopup.xaml
  LotCoMPrinter/Views/ReprintListPopup.xaml.cs
Labels: enhancement

#212 feature/210
  .github/workflows/cicd.yml
  LotCoMPrinter/Models/Datasources/PrintHistory.cs
  LotCoMPrinter/Models/Datatypes/PartialDataSet.cs
  LotCoMPrinter/Models/Exceptions/DatabaseException.cs
  LotCoMPrinter/Models/Exceptions/ProcessNameException.cs
  LotCoMPrinter/Setup/LotComPrinterSetup.exe
  LotCoMPrinter/Setup/LotComPrinterSetup.exe.config
  LotCoMPrinter/Setup/WixSharp.Msi.dll
  LotCoMPrinter/Setup/WixSharp.MsiEventHost.exe
  LotCoMPrinter/Setup/WixSharp.UI.WPF.dll
  LotCoMPrinter/Setup/WixSharp.UI.dll
  LotCoMPrinter/Setup/WixSharp.dll
  LotCoMPrinter/Setup/WixToolset.Dtf.WindowsInstaller.dll
  LotCoMPrinter/Setup/WixToolset.Mba.Core.dll
  LotCoMPrinter/Setup/mbanative.dll
  LotCoMPrinter/Views/MainPage.xaml
  LotCoMPrinter/Views/MainPage.xaml.cs
Labels: documentation, enhancement

#213 0.8.0.0-release
  .github/workflows/cicd.yml
  CHANGELOG.md
  LotCoMPrinter/LotCoMPrinter.csproj
  LotCoMPrinter/Models/Datasources/PrintHistory.cs
  LotCoMPrinter/Models/Datatypes/PartialDataSet.cs
  LotCoMPrinter/Models/Datatypes/PrintJob.cs
  LotCoMPrinter/Models/Enums/PrintJobType.cs
  LotCoMPrinter/Platforms/Windows/Package.appxmanifest
  LotCoMPrinter/Platforms/Windows/app.manifest
  LotCoMPrinter/Resources/Styles/Styles.xaml
  LotCoMPrinter/Setup/LotComPrinterSetup.exe
  LotCoMPrinter/Setup/LotComPrinterSetup.exe.config
  LotCoMPrinter/Setup/WixSharp.Msi.dll
  LotCoMPrinter/Setup/WixSharp.MsiEventHost.exe
  LotCoMPrinter/Setup/WixSharp.UI.WPF.dll
  LotCoMPrinter/Setup/WixSharp.UI.dll
  LotCoMPrinter/Setup/WixSharp.dll
  LotCoMPrinter/Setup/WixToolset.Dtf.WindowsInstaller.dll
  LotCoMPrinter/Setup/WixToolset.Mba.Core.dll
  LotCoMPrinter/Setup/mbanative.dll
  LotCoMPrinter/ViewModels/MainPageViewModel.cs
  LotCoMPrinter/Views/MainPage.xaml
  LotCoMPrinter/Views/MainPage.xaml.cs
  LotCoMPrinter/Views/ProcessSelectionPopup.xaml
  LotCoMPrinter/Views/ProcessSelectionPopup.xaml.cs
  LotCoMPrinter/Views/ReprintListPopup.xaml
  LotCoMPrinter/Views/ReprintListPopup.xaml.cs
Labels: bug, documentation, enhancement

#215 feature/207
  LotCoMPrinter/Models/Datasources/PrintTicketCache.cs
  LotCoMPrinter/Resources/Images/edit.svg
  LotCoMPrinter/Resources/Images/menu.svg
  LotCoMPrinter/Resources/Images/plus.svg
  LotCoMPrinter/ViewModels/MainPageViewModel.cs
  LotCoMPrinter/ViewModels/TicketEditorPageViewModel.cs
  LotCoMPrinter/Views/MainPage.xaml
  LotCoMPrinter/Views/MainPage.xaml.cs
  LotCoMPrinter/Views/TicketActionsPanelPopup.xaml
  LotCoMPrinter/Views/TicketActionsPanelPopup.xaml.cs
  LotCoMPrinter/Views/TicketEditorPage.xaml
  LotCoMPrinter/Views/TicketEditorPage.xaml.cs
Labels: enhancement

#222 feature/221
  LotCoMPrinter/Models/Services/LabelGenerator.cs
  LotCoMPrinter/Models/Services/PrintLogger.cs
  LotCoMPrinter/Views/TicketEditorPage.xaml
  LotCoMPrinter/Views/TicketEditorPage.xaml.cs
Labels: enhancement

#223 feature/220
  LotCoMPrinter/Models/Datatypes/PrintTicket.cs
  LotCoMPrinter/Models/Datatypes/TrackedPrintTicket.cs
  LotCoMPrinter/Models/Services/PrintLogger.cs
  LotCoMPrinter/Resources/Images/annotation_warning.svg
  LotCoMPrinter/ViewModels/TicketReprintEditorPageViewModel.cs
  LotCoMPrinter/Views/MainPage.xaml.cs
  LotCoMPrinter/Views/ProcessSelectionPopup.xaml.cs
  LotCoMPrinter/Views/ReprintSelectionPopup.xaml
  LotCoMPrinter/Views/ReprintSelectionPopup.xaml.cs
  LotCoMPrinter/Views/TicketReprintEditorPage.xaml
  LotCoMPrinter/Views/TicketReprintEditorPage.xaml.cs
Labels: enhancement
